#!/usr/bin/env bash

set -e

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
PROJECT_DIR="$(dirname "$SCRIPT_PATH")"

cd "$PROJECT_DIR"

CONFIG_FILE="$PROJECT_DIR/.soundcloud9000.env"

if [[ -f "$CONFIG_FILE" ]]; then
  source "$CONFIG_FILE"
fi

export SC_USERNAME="${SC_USERNAME:-vsalles82}"

exec bundle _2.7.2_ exec ruby \
  -Ilib \
  -rsoundcloud9000 \
  -e 'Soundcloud9000.start' \
  -- "$@"
